font pango:monospace 10
default_border pixel 1
default_floating_border pixel 1
focus_follows_mouse no
mouse_warping output
xwayland disable

output HEADLESS-1 mode 1280x720@30Hz
output HEADLESS-1 bg #050708 solid_color

seat seat0 fallback true
seat seat0 hide_cursor 0

set $mod Mod4
bindsym $mod+Return exec kitty --title EutherGate-Forge
bindsym $mod+d exec kitty --title EutherGate-Forge

bar {
    position top
    status_command $HOME/EutherGate/scripts/forge-status.sh
    tray_output none
    colors {
        background #080b0d
        statusline #b8ff5a
        separator #52616a
        focused_workspace #b8ff5a #182016 #050708
        inactive_workspace #20282d #080b0d #8b979d
    }
}

exec kitty --title EutherGate-Forge
